# General config
root            :
weights         :
model           :
project         :
name            :
save_dir        :
device          : 0
imgsz           : 512
epochs          : 1000
exist_ok        : False
verbose         : True
# Model
load_pretrain   : False
beta            : 1
# Data
data            :
train_batch_size: 16
val_batch_size  : 8
num_workers     : 5
# Training
lr              : 0.0001
weight_decay    : 0.00005
grad_clip_norm  : 0.1
display_iter    : 10
checkpoint_iter : 10
