# Basic
hostname    : ~
config      : ~
arch        : "lyt_net"
model       : "lyt_net"
data        : "lol_v1"
data_dir    : "data/enhance/llie/lol_v1"
root        : ~
project     : ~
variant     : ~
fullname    : "lyt_net_lol_v1"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/lyt_net/lyt_net/lol_v1/lyt_net_lol_v1.pth"
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 1500
steps       : ~
imgsz       : 256
resize      : ~
benchmark   : False
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
lr: 0.0002
