# Basic
hostname    : ~
config      : ~
arch        : "c2pnet"
model       : "c2pnet"
data        : "reside_ots"
data_dir    : "data/enhance/reside/ots"
root        : ~
project     : ~
variant     : ~
fullname    : "c2pnet_reside_ots"
save_dir    : ~
weights     : ~
device      : 0
local_rank  : -1
launcher    : ~
epochs      : ~
steps       : 1000000
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
