# Basic
hostname    : ~
config      : ~
arch        : "kind"
model       : "kind"
data        : "lol_v1"
data_dir    : "data/enhance/llie/lol_v1"
root        : ~
project     : ~
variant     : ~
fullname    : "kind_lol_v1"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/kind/kind/lol_v1"
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 401
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : False
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
batch_size     : 32
length         : 256
steps_per_epoch: 128
print_frequency: 10
save_frequency : 10
samples_dir    : "./samples"
weights_dir    : "./checkpoints"
learning_rate  : 0.0004
checkpoints    : True
noDecom        : False
