# General config
root        : ~
weights     : ~  # (== model_pretrain)
model       : "zeroig"
data        : ~
fullname    : "zeroig"
save_dir    : ~
device      : 0
epochs      : 2001
steps       : ~
seed        : 2
imgsz       : 512
resize      : ~
benchmark   : ~
save_image  : ~
use_data_dir: ~
exist_ok    : False
verbose     : True

# Training
batch_size  : 32
num_workers : 0
lr          : 0.0003
