#
#     /\_____/\
#    /  o   o  \
#   ( ==  ^  == )
#    )         (
#   (           )
#  ( (  )   (  ) )
# (__(__)___(__)__)
#
[tool.poetry]
name          = "mon"
version       = "1.2.9"
description   = "MON covers a wide range of research topics in computer vision, machine learning, and deep learning."
license       = "MIT"
authors       = [
    "Long H. Pham <longpham3105@gmail.com>",
]
maintainers   = [
    "Long H. Pham <longpham3105@gmail.com>",
]
readme        = "README.md"
repository    = "https://github.com/phlong3105/one"
documentation = "https://github.com/phlong3105/one/docs"
keywords      = [
    "computer vision",
    "image processing",
    "deep learning",
    "research",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
]
packages = [
    {include="mon",  from="src"    },
    {include="supr", from="src/app"},
]
include = [
    "CHANGELOG.md",
    "GUIDELINE.md",
    "README.md",
    "install.sh",
    "linux.yaml",
    "mac.yaml",
    "server.yaml",
]
exclude = []

[tool.poetry.dependencies]
python         = ">=3.8, <3.12"
addict         = {version="*", optional=true}
cog            = {version="*", optional=true}
easydict       = {version="*", optional=true}
hydra-core     = {version="*", optional=true}
mediapipe      = {version="*", optional=true}
pandas         = {version="*", optional=true}
tensorflow     = {version="*", optional=true}
torchfile      = {version="*", optional=true}
webdataset     = {version="*", optional=true}
saicinpainting = {path="src/lib/vision/enhance/inpaint/lama", develop=true}
ultralytics    = {path="src/lib/vision/detect/yolov8", develop=true}

[tool.poetry.extras]
dev = ["ultralytics"]
aic = [
    "addict", "cog", "easydict", "hydra-core", "kornia", "mediapipe", "pandas",
    "tensorflow", "torchfile", "saicinpainting", "ultralytics",
]

# [tool.poetry.group.dev]
# optional = true

# [tool.poetry.group.dev.dependencies]
# ultralytics = {path="src/lib/yolov8", develop=true}

[build-system]
requires      = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
# build-backend = "setuptools.build_meta"


# Comments
#
# 1. Fix thop error: AttributeError: 'some_object' object has no attribute 'total_ops'
# pip install --upgrade git+https://github.com/sile/pytorch-OpCounter.git@8f115d4aeaee787d7347b75f30be28164b02ccaa
