# Basic
hostname    : ~
config      : ~
arch        : "snr_net"
model       : "snr_net"
data        : "lol_v1"
data_dir    : "data/enhance/lol_v1"
root        : ~
project     : ~
variant     : ~
fullname    : "snr_net_lol_v1"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/snr_net/snr_net/lol_v1/snr_net_lol_v1.pth"
device      : 0
local_rank  : ~
launcher    : ~
epochs      : 1000
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : False
save_image  : True
save_debug  : True
use_data_dir: False
use_fullpath: False
use_fullname: True
exist_ok    : True
verbose     : True

# Misc
opt_path: "lol_v1.yaml"
