weights          :
project          :
name             :
device           : 0
exist_ok         : True
verbose          : True

# Data loader related
data             : "lol_v1"
imgsz            : 256       # resized image size for training
crop_size        : 216       # cropped image size for training
batch_size       : 2         # batch size
in_channels_a    : 3         # # of input channels for the domain A
in_channels_b    : 3         # # of input channels for the domain B
no_flip          : False     # specified if no flipping
a2b              : 1         # translation direction, 1 for a2b, 0 for b2a

# Output related
display_dir      : "../logs"
result_dir       : "../results"
display_freq     : 1         # freq (iteration) of display
img_save_freq    : 1         # freq (epoch) of saving images
model_save_freq  : 100       # freq (epoch) of saving models
no_display_img   : False     # specified if no display
num              : 5         # number of outputs per image

# Training related
no_ms            : False     # disable mode seeking regularization
concat           : 1         # concatenate attribute features for translation, set 0 for using feature-wise transform
gpu              : 0
dis_scale        : 3         # scale of discriminator
dis_norm         : None      # normalization layer in discriminator [None, Instance]
dis_spectral_norm: False     # use spectral normalization in discriminator
lr_policy        : "lambda"  # type of learning rate decay
epochs           : 1200      # number of epochs
n_epochs_decay   : 600       # epoch start decay learning rate, set -1 if no decay
resume           : None      # specified the dir of saved models for resume the training
d_iter           : 3         # # of iterations for updating content discriminator
content_share    : False     # set content encoder shared
dataset          : "pair"    # path for saving result images and models
vgg              : 0         # use perceptual loss
vgg_choose       : "relu5_1" # choose layer for vgg
vgg_mean         : False     # subtract mean in vgg loss
no_vgg_instance  : False     # vgg instance normalization
attribute_share  : False     # set attribute encoder shared
