weights     :
data        : "lol_v2_real"
project     :
name        :
device      : 0
imgsz       : 384
epochs      : 100
batch_size  : 4
lr          : 0.00001
loss_weights: [0.35, 0.10, 0.25, 0.30]
exist_ok    : True
verbose     : True
