# General config
root        :
weights     :
model       :
project     :
name        :
device      : 0
imgsz       : 384
epochs      : 100
exist_ok    : True
verbose     : True
# Data
data        : "lol_v1"
batch_size  : 4
# Loss
loss_weights: [0.40, 0.05, 0.15, 0.40]
# Training
lr          : 0.00001
