project         :
name            :
weights         :
device          : 0
imgsz           : 512
epochs          : 200
lr              : 0.0001
weight_decay    : 0.0001
grad_clip_norm  : 0.1
train_batch_size: 32
val_batch_size  : 4
num_workers     : 4
display_iter    : 10
checkpoint_iter : 10
exist_ok        : True
verbose         : True
