# Basic
hostname    : ~
config      : ~
arch        : "fourllie"
model       : "fourllie"
data        : "lsrw_huawei"
data_dir    : "data/enhance/lsrw_huawei"
root        : ~
project     : ~
variant     : ~
fullname    : "fourllie_lsrw_huawei"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/fourllie/fourllie/lsrw_huawei/fourllie_lsrw_huawei.pth"
device      : 0
local_rank  : ~
launcher    : ~
epochs      : 1000
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : False
save_image  : True
save_debug  : True
use_data_dir: False
use_fullpath: False
use_fullname: True
exist_ok    : True
verbose     : True

# Model Specific
opt_path: "lsrw_huawei.yaml"
