# Basic
hostname    : ~
config      : ~
arch        : "fourllie"
model       : "fourllie"
data        : "lol_v2_real"
data_dir    : "data/enhance/lol_v2_real"
root        : ~
project     : ~
variant     : ~
fullname    : "fourllie_lol_v2_real"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/fourllie/fourllie/lol_v2_real/fourllie_lol_v2_real.pth"
device      : 0
local_rank  : ~
launcher    : ~
epochs      : 1000
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : False
save_image  : True
save_debug  : True
use_data_dir: False
use_fullpath: False
use_fullname: True
exist_ok    : True
verbose     : True

# Misc
opt_path: "lol_v2_real.yaml"
