# Basic
hostname    : ~
config      : ~
arch        : "zero_didce"
model       : "zero_didce"
data        : "sice_mix"
data_dir    : "data/enhance/llie/sice_mix"
root        : ~
project     : ~
variant     : ~
fullname    : "zero_didce_sice_mix"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/zero_didce/zero_didce/sice_mix/zero_didce_sice_mix.pth"
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 200
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
load_pretrain   : False
train_batch_size: 32
val_batch_size  : 4
num_workers     : 4
lr              : 0.0001
weight_decay    : 0.0001
grad_clip_norm  : 0.1
display_iter    : 10
checkpoint_iter : 10
