# Basic
hostname    : ~
config      : ~
arch        : "ruas"
model       : "ruas"
data        : "lol_v1"
data_dir    : "data/enhance/llie/lol_v1"
root        : ~
project     : ~
variant     : ~
fullname    : "ruas_lol_v1"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/ruas/ruas/lol_v1/ruas_darkface.pt"
device      : 0
local_rank  : -1
launcher    : ~
epochs      : ~
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
seed: 2
