# Basic
hostname    : ~
config      : ~
arch        : "neurop"
data        : "ppr10k_b"
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : "neurop_ppr10k_b"
save_dir    : ~
weights     : "zoo/vision/enhance/retouch/neurop/neurop/ppr10k_b/neurop_ppr10k_b.pth"
device      : 0
local_rank  : ~
launcher    : ~
epochs      : ~
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
opt_path: "neurop_ppr10k_b.yaml"
