# Basic
hostname    : ~
config      : ~
arch        : "c2pnet"
model       : "c2pnet"
data        : "reside_ots"
data_dir    : "data/enhance/reside/ots"
root        : ~
project     : ~
variant     : ~
fullname    : "c2pnet_reside_ots"
save_dir    : ~
weights     : ~
device      : 0
local_rank  : -1
launcher    : ~
epochs      : ~
steps       : 1000000
imgsz       : 512
resize      : ~
benchmark   : False
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
use_fullname: False
exist_ok    : True
verbose     : True

# Model Specific
eval_step    : 5000
lr           : 0.0001
gps          : 3
blocks       : 19
bs           : 2
crop         : False
crop_size    : 240
no_lr_sche   : False
cl_lambda    : 0.25
loss_weight  : 0.2
clcrloss     : False
norm         : False
ablation_type: 0
clip         : False
beta1        : 0.9
beta2        : 0.999
