# Basic
hostname    : ~
config      : ~
arch        : "sci"
model       : "sci"
data        : "darkface"
data_dir    : "data/enhance/llie/darkface"
root        : ~
project     : ~
variant     : ~
fullname    : "sci_darkface"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/sci/sci/darkface/sci_darkface.pt"
device      : 0
local_rank  : -1
launcher    : ~
epochs      : ~
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True
