# Basic
hostname    : ~
config      : ~
arch        : "stablellve"
model       : "stablellve"
data        : ~
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : ~
save_dir    : ~
weights     : "zoo/vision/enhance/llie/stablellve/stablellve/custom/stablellve_custom.pth"
device      : 0
local_rank  : -1
launcher    : ~
epochs      : ~
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True
