# Basic
hostname    : ~
config      : ~
arch        : "llflow"
model       : "llflow"
data        : "lol_v1"
data_dir    : "enhance/llie/lol_v1"
root        : ~
project     : ~
variant     : ~
fullname    : "llflow_lol_v1"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/llflow/llflow/lol_v1/llflow_lol_v1.pth"
device      : 0
local_rank  : ~
launcher    : ~
epochs      : 1000
steps       : ~
imgsz       : 256
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
opt_path: "lol_v1.yaml"
