# Basic
hostname    : ~
config      : ~
arch        : "retinexformer"
data        : "sid"
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : "retinexformer_sid"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/retinexformer/retinexformer/sid/retinexformer_sid.pth"
device      : 0
local_rank  : ~
launcher    : ~
epochs      : ~
steps       : 300000
imgsz       : 512
resize      : ~
benchmark   : False
save_image  : True
save_debug  : True
use_data_dir: False
use_fullpath: False
use_fullname: True
exist_ok    : True
verbose     : True

# Model Specific
opt_path: "sid.yaml"
