# Basic
hostname    : ~
config      : ~
arch        : "retinexformer"
data        : "lol_v2_synthetic"
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : "retinexformer_lol_v2_synthetic"
save_dir    : ~
weights     : "zoo/vision/enhance/llie/retinexformer/retinexformer/lol_v2_synthetic/retinexformer_lol_v2_synthetic.pth"
device      : 0
local_rank  : ~
launcher    : ~
epochs      : ~
steps       : 300000
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
opt_path: "lol_v2_synthetic.yaml"
