# Basic
hostname    : ~
config      : ~
arch        : "colie"
model       : "colie"
data        : "sice_mix"
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : "colie_sice_mix"
save_dir    : ~
weights     : ~
device      : 0
local_rank  : -1
launcher    : ~
epochs      : 100
steps       : ~
imgsz       : 256
resize      : ~
benchmark   : False
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True

# Model Specific
window: 7    # context window size
L     : 0.5
alpha : 1
beta  : 20
gamma : 8
delta : 5
