# Basic
hostname    : ~
config      : ~
arch        : "retinexnet"
model       : "retinexnet"
data        : "lol_v1"
data_dir    : ~
root        : ~
project     : ~
variant     : ~
fullname    : "retinexnet_lol_v1"
save_dir    : ~
weights     : ~
device      : 0
local_rank  : -1
launcher    : ~
epochs      : ~
steps       : ~
imgsz       : 512
resize      : ~
benchmark   : True
save_image  : True
save_debug  : False
use_data_dir: False
use_fullpath: False
exist_ok    : False
verbose     : True
