# General config
root            :
weights         :
model           :
project         :
name            :
save_dir        :
device          : 0
imgsz           : 512     # Inference size
epochs          : 300
exist_ok        : True
verbose         : True
# Data
data            :
image_h         : 1200
image_w         : 900
image_ds        : 256
train_batch_size: 8
val_batch_size  : 4
num_workers     : 4
# Loss
zerodce         : False
tv_loss         : False
color_loss      : False
l2_loss         : False
cos_loss        : False
mul_loss        : False
no_l1           : False
# Training
load_pretrain   : False
parallel        : False
lr              : 0.0001
lr_type         : "fix"
weight_decay    : 0.0001
grad_clip_norm  : 1
display_iter    : 10
snapshot_iter   : 10
